In [2]:
import numpy as np

# 2.Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입

## 2.1 배열 생성

In [3]:
a = list(range(10))
np.array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

직접생성

In [4]:
np.array([[1, 2, 3], [4, 5, 6]],dtype=float).shape

(2, 3)

In [5]:
a = list(range(10))

In [6]:
np.array(a) + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2.1.1 기본 배열 생성

#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [7]:
list(np.arange(1.2, 10.5))

[1.2,
 2.2,
 3.2,
 4.200000000000001,
 5.200000000000001,
 6.200000000000001,
 7.200000000000002,
 8.200000000000001,
 9.200000000000001,
 10.200000000000001]

In [9]:
y = np.arange(-5, 5, 0.5, dtype=int)
y

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14])

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [11]:
np.linspace(1, 5, num=10, endpoint=False)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

#### eye

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1)
```

In [14]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [16]:
np.eye(5, k=-1) + np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.]])

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5)
x = np.zeros((5, 2), dtype=float)
```

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((5, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

In [26]:
np.full((5, 2), np.nan)

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

In [27]:
np.tril([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [28]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

In [29]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [30]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

### 2.1.2 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

In [52]:
np.random.seed(0)

In [53]:
np.random.random(size=(2, 3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [58]:
np.random.randint(0, 10, size=(5,2))

array([[0, 0],
       [4, 5],
       [5, 6],
       [8, 4],
       [1, 4]])

#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

In [60]:
np.random.normal(loc=10, scale=20, size=(3, 5))

array([[-11.71601191,  22.7947199 ,   2.28273327,  -5.51524707,
         29.91422697],
       [-28.66409559,  14.97061255,   9.37509329,   7.21052075,
          6.18688042],
       [ 18.97275055,  -9.84859543,   5.48120689, -23.09141533,
         -2.79445275]])

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

In [61]:
np.random.randn(3, 5)

array([[-0.4794198 ,  0.3113635 , -0.77602047, -0.30736481, -0.36652394],
       [ 1.11971196, -0.45792242,  0.4253934 , -0.02797118,  1.47598983],
       [ 0.6467801 , -0.36433431, -0.67877739, -0.35362786, -0.74074747]])

## 2.2 배열 조작

인덱싱 & 슬라이싱

In [66]:
a = np.random.randint(0, 10, size=(2, 5))

In [67]:
a

array([[6, 8, 2, 3, 0],
       [0, 6, 0, 6, 3]])

In [73]:
# 6 -> 10
# 9, 7 -> 20
# 4, 3 -> 30

a[0, 3] = 10
a[1, 3:] = 20
a[:, 2] = 30
a

array([[ 6,  8, 30, 10,  0],
       [ 0, 20, 30, 20, 20]])

In [72]:
a[:,1][1] = 20

In [64]:
b = [[1, 2], [3, 4], [5, 6]]

In [65]:
b[1][0]

3

### 2.2.1 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

In [2]:
import numpy as np

In [6]:
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [8]:
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11]])

In [9]:
a = np.arange(24).reshape(2, 3, 4)
b = np.arange(24).reshape(2, 3, 4)

np.concatenate([a, b], axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
np.concatenate([a, b], axis=1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
np.concatenate([a, b], axis=2)

array([[[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 12, 13, 14, 15],
        [16, 17, 18, 19, 16, 17, 18, 19],
        [20, 21, 22, 23, 20, 21, 22, 23]]])

In [13]:
b = np.arange(36).reshape(3, 3, 4)
np.concatenate([a,b], axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [15]:
a= np.array([1, 2, 3])
np.concatenate([a,[4]])

array([1, 2, 3, 4])

### 2.2.2 배열 분할

#### array_split

주어진 배열을 분할 <br>
<br>

사용법
```python
x = np.arange(9.0)
np.array_split(x, 3)
np.array_split(x, [3, 5, 6, 10])
```

In [19]:
x = np.arange(10)
assert len(x) % 3 ==0
np.array_split(x, 3)

AssertionError: 

In [20]:
np.array_split(x, [2, 3, 4])

[array([0, 1]), array([2]), array([3]), array([4, 5, 6, 7, 8, 9])]

### 2.2.3 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


In [22]:
x = np.arange(30)
x.reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [23]:
x.reshape(1, 5, 6, 1)

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14],
         [15],
         [16],
         [17]],

        [[18],
         [19],
         [20],
         [21],
         [22],
         [23]],

        [[24],
         [25],
         [26],
         [27],
         [28],
         [29]]]])

#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

In [24]:
x = np.arange(30).reshape(2, 5, 3)
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

In [25]:
x = np.arange(3).reshape(3, 1, 1)
x.squeeze()

array([0, 1, 2])

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

In [34]:
x = np.arange(10)
np.expand_dims(x, 0) # d o y o u k n o w r i c h g a y ?

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 2.2.4 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

In [42]:
x = np.arange(20).reshape(4, 5)
print(x)
print(np.roll(x, 1, axis=0))
print(np.roll(x, 1, axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[15 16 17 18 19]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 4  0  1  2  3]
 [ 9  5  6  7  8]
 [14 10 11 12 13]
 [19 15 16 17 18]]


##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


In [45]:
x = np.arange(10).reshape(5, 2)
print(x)
print(np.flip(x,1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[1 0]
 [3 2]
 [5 4]
 [7 6]
 [9 8]]


방법 2

In [46]:
print(x[::-1, :])
print(x[:, :: -1])

[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]
[[1 0]
 [3 2]
 [5 4]
 [7 6]
 [9 8]]


### 2.2.5 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxes(0, 2)    # 0 <-> 2
```

In [48]:
x = np.arange(100).reshape(5, 2, 10)
x.swapaxes(0 , 2).shape

(10, 2, 5)

In [50]:
x = np.arange(24).reshape(2, 3, 4)
print(x.swapaxes(0, 2).shape)
x.reshape(4, 3, 2)
print(x.swapaxes(0,2).shape)

(4, 3, 2)
(4, 3, 2)


reshape vs swapaxes 

reshape : 자기가 원하는대로 데이터 지정
swapaxes : 축을 바꿨다. 

#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

In [52]:
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)
x.transpose(2, 0, 1)

array([[[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]],

       [[ 1, 11],
        [21, 31],
        [41, 51],
        [61, 71],
        [81, 91]],

       [[ 2, 12],
        [22, 32],
        [42, 52],
        [62, 72],
        [82, 92]],

       [[ 3, 13],
        [23, 33],
        [43, 53],
        [63, 73],
        [83, 93]],

       [[ 4, 14],
        [24, 34],
        [44, 54],
        [64, 74],
        [84, 94]],

       [[ 5, 15],
        [25, 35],
        [45, 55],
        [65, 75],
        [85, 95]],

       [[ 6, 16],
        [26, 36],
        [46, 56],
        [66, 76],
        [86, 96]],

       [[ 7, 17],
        [27, 37],
        [47, 57],
        [67, 77],
        [87, 97]],

       [[ 8, 18],
        [28, 38],
        [48, 58],
        [68, 78],
        [88, 98]],

       [[ 9, 19],
        [29, 39],
        [49, 59],
        [69, 79],
        [89, 99]]])

### 2.2.6 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



In [53]:
x = np.random.randint(0, 10, (5, 2))
x

array([[4, 6],
       [0, 5],
       [2, 8],
       [3, 8],
       [4, 6]])

In [56]:
x.sort(axis=0)
print(x)
x.sort(axis=1)
print(x)

[[0 5]
 [2 6]
 [3 6]
 [4 8]
 [4 8]]
[[0 5]
 [2 6]
 [3 6]
 [4 8]
 [4 8]]


#### argsort

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


In [58]:
x = np.random.randint(0, 10, 10)
x

array([3, 4, 9, 3, 6, 3, 6, 0, 4, 7])

In [59]:
x.argsort()

array([7, 0, 3, 5, 1, 8, 4, 6, 9, 2], dtype=int64)

### 2.2.7 기타

##### unique

축을 기준으로 배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

In [63]:
np.unique(np.array([1, 1, 1, 2, 3, 4]))
x = np.random.randint(0, 10, (5, 2))

In [64]:
print(np.unique(x, axis=0))
print(np.unique(x, axis=1))

[[1 4]
 [4 0]
 [8 9]
 [9 3]
 [9 6]]
[[3 9]
 [4 1]
 [0 4]
 [9 8]
 [6 9]]


#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환 <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


In [66]:
x = np.full((3, 4), np.nan)
np.nan_to_num(x,nan=1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(x, trip='f')    # 앞의 0만 제거
np.trim_zeros(x, trip='b')    # 뒤의 0만 제거
np.trim_zeros(x, trip='fb')   # 앞뒤 0 제거
```

In [67]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
print(np.trim_zeros(x,trim='f'))
print(np.trim_zeros(x,trim='b'))
print(np.trim_zeros(x,trim='fb'))

[1 2 3 0 2 1 0]
[0 0 0 1 2 3 0 2 1]
[1 2 3 0 2 1]


stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

In [70]:
x=np.arange(1, 11)
y = np.lib.stride_tricks.sliding_window_view(x, 3)

[array([1, 2, 3]),
 array([2, 3, 4]),
 array([3, 4, 5]),
 array([4, 5, 6]),
 array([5, 6, 7]),
 array([6, 7, 8]),
 array([7, 8, 9]),
 array([ 8,  9, 10])]

## 2.3 배열 탐색

### argmax

축을 기준으로 배열에서 최댓걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

In [73]:
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=1)

array([2, 2], dtype=int64)

In [74]:
x = np.random.randint(0, 10, (2, 3))
print(x)

[[2 8 4]
 [9 4 8]]


### argmin

축을 기준으로 배열에서 최솟걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



In [75]:
x = np.random.randint(0, 20, (5, 4))
x

array([[18,  9, 10,  6],
       [11, 15, 13, 16],
       [ 3,  4, 11, 10],
       [11, 13, 17,  3],
       [ 3,  5,  7,  9]])

### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

In [76]:
x = np.random.randint(0, 20, (5, 4))
x

array([[10,  3,  6, 18],
       [10, 14, 11, 15],
       [ 2, 10, 10,  4],
       [16,  2,  5,  3],
       [18,  6,  1,  9]])

In [81]:
np.where(x < 10)

(array([0, 0, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int64),
 array([1, 2, 0, 3, 1, 2, 3, 1, 2, 3], dtype=int64))

In [80]:
np.where(x < 10, x, x-10)

array([[0, 3, 6, 8],
       [0, 4, 1, 5],
       [2, 0, 0, 4],
       [6, 2, 5, 3],
       [8, 6, 1, 9]])

### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

In [82]:
x = np.random.randint(0, 20, (5, 4))
np.extract(x < 10, x)

array([1, 8, 4, 7, 2, 3, 7, 8, 7, 7])

##  2.4 배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

In [83]:
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

In [ ]:
# 원소별 곱
x * y

In [84]:
# 행렬 곱
x@y

array([[16, 32],
       [30, 59]])

### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



In [89]:
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)

(array([-1.,  8.]),
 array([[-0.96152395, -0.70710678],
        [ 0.27472113, -0.70710678]]))

### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

In [93]:
x = np.random.randint(0, 10, size=(2,2))
print(x)
np.linalg.det(x)

[[1 2]
 [7 9]]


-5.000000000000001

### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

In [94]:
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)

array([-1.,  1.])

inv

역행렬 반환 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

In [110]:
x = np.random.randint(0, 10, size=(2,2))
print(x)
print(np.linalg.inv(x))

[[5 6]
 [1 4]]
[[ 0.28571429 -0.42857143]
 [-0.07142857  0.35714286]]


## 2.5 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

In [112]:
x = np.arange(12).reshape(4,3)
print(x)
x.ptp(axis=0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([9, 9, 9])

#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

In [113]:
x = np.random.randint(0, 10, size=(4, 3))
x

array([[4, 2, 9],
       [9, 8, 8],
       [9, 2, 8],
       [2, 9, 0]])

In [114]:
np.median(x, axis=0)

array([6.5, 5. , 8. ])

### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

In [116]:
x.sum(axis=1)

array([15, 25, 19, 11])

### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

In [117]:
x= np.array([3, 4, 5])
np.average(x, weights=[1, 1, 2])

4.25

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

In [120]:
x.mean(axis=0)

array([4.5 , 5.75, 3.75])

### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

In [123]:
x = np.random.randint(0,10,(4,3))
x.min(axis=1)

array([1, 3, 0, 2])

### max

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

In [124]:
x = np.random.randint(0,10,(4,3))
x.max(axis=1)

array([8, 9, 8, 7])

### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

In [125]:
x = np.random.randint(0,10,(4,3))
x.std(axis=1)

array([1.63299316, 1.41421356, 0.81649658, 2.3570226 ])

### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```

In [133]:
x = np.random.rand(25).reshape(5,5)
x

array([[0.65870568, 0.43996674, 0.79231967, 0.12937491, 0.76956086],
       [0.55491962, 0.57160512, 0.3481843 , 0.30067467, 0.54747738],
       [0.62816271, 0.89027598, 0.07878757, 0.56272212, 0.40264452],
       [0.83901485, 0.59160638, 0.38261087, 0.15223598, 0.81452238],
       [0.4645159 , 0.91734293, 0.41615768, 0.6027845 , 0.18544313]])

In [134]:
np.cov(x)

array([[ 0.07686416,  0.01424579, -0.04483429,  0.05285665, -0.0457706 ],
       [ 0.01424579,  0.01672513,  0.02100608,  0.03429247,  0.00207431],
       [-0.04483429,  0.02100608,  0.08969738,  0.01817713,  0.05740941],
       [ 0.05285665,  0.03429247,  0.01817713,  0.08532205, -0.0258664 ],
       [-0.0457706 ,  0.00207431,  0.05740941, -0.0258664 ,  0.07262171]])

In [136]:
np.array([3,4,5],[6,7,8]).T

TypeError: Field elements must be 2- or 3-tuples, got '6'