# NAVER 뉴스 데이터를 이용하여서 데이터 추출하기

## BeautifulSoup, Requests, Pandas 모듈 생성하기

데이터베이스 불러오기

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

뉴스별 데이터베이스 부르기

In [2]:
# chosun_eilbo_database = pd.read_csv(r'C:\bigdata_git\bigdata_thunder\bigdata1\chosun_eilbo.csv', encoding='cp949', index_col=False)
# korean_economy_database = pd.read_csv(r'C:\bigdata_git\bigdata_thunder\bigdata1\korean_economy.csv', encoding='utf-8', index_col=False)
# mail_economy_database = pd.read_csv(r'C:\bigdata_git\bigdata_thunder\bigdata1\mail_economy.csv', encoding='utf-8', index_col=False)
# midlle_eilbo_database = pd.read_csv(r'C:\bigdata_git\bigdata_thunder\bigdata1\middle_eilbo.csv', encoding='utf-8', index_col=False)
# money_today_database = pd.read_csv(r'C:\bigdata_git\bigdata_thunder\bigdata1\money_today.csv', encoding='utf-8', index_col=False)
chosun_eilbo_database = pd.read_csv(r'C:\Users\user\Documents\github\bigdata_thunder\bigdata1\chosun_eilbo.csv', encoding='cp949', index_col=False)
korean_economy_database = pd.read_csv(r'C:\Users\user\Documents\github\bigdata_thunder\bigdata1\korean_economy.csv', encoding='utf-8', index_col=False)
mail_economy_database = pd.read_csv(r'C:\Users\user\Documents\github\bigdata_thunder\bigdata1\mail_economy.csv', encoding='utf-8', index_col=False)
midlle_eilbo_database = pd.read_csv(r'C:\Users\user\Documents\github\bigdata_thunder\bigdata1\middle_eilbo.csv', encoding='utf-8', index_col=False)
money_today_database = pd.read_csv(r'C:\Users\user\Documents\github\bigdata_thunder\bigdata1\money_today.csv', encoding='utf-8', index_col=False)


데이터베이스 테스트하기

In [3]:
chosun_eilbo_database = chosun_eilbo_database.dropna()
chosun_eilbo_database.head(100)

title  \
0                  판다는 언제부터 대나무만 먹었을까? 600만년 전 화석 봤더니…   
1                    이준석 변호인 징계요청 기각… 경기변호사회 “수사결과 봐야”   
2                박지현 “이광재가 내 배후? 어리면 배후 있을 거라는 꼰대식 사고”   
3                       野 당권주자들 “검수완박 성급했다” 이제와서 반성 모드   
4                 “먹으니 시야 흐려져” 시누이 부부 음식에 메탄올 넣은 30대여성   
..                                                 ...   
98              여당서도 김승희 반대 목소리…성일종 “후원금 논란, 바람직하지 않아”   
99                     박지원 “尹 첫 해외순방 80점, 김건희 여사는 90점”   
100             여름 휴가지 맛집 일일이 안 찾아도 네이버 AI가 한꺼번에 검색해준다   
101  흠뻑쇼 120만원·토트넘 3700만원…‘암표 거지와의 전쟁’ 아무 소용없는 이유 [...   
102     상반기 美 증시, 52년 만의 최대 하락 폭... 닥터 둠 “50% 더 떨어질 것”   

                                               content  label  \
0    통통한 몸집과 어울리지 않게 대나무를 주식으로 하는 판다. 이런 판다의 독특한 식성...      0   
1    “가세연의 이준석 녹취는 일부 삭제된 것” 경기중앙지방변호사회가 한 보수단체가 제기...      0   
2    비대위원장직 자진사퇴 후 한 달 만에 공개행사 참석 이재명 전당대회 출마와 민형배 ...      0   
3    강병원 “진영 논리서 벗어나야” 박용진 “상식 복원하는 게 혁신” 꼼수 탈당한 민형...      0   
4    시누이 부부가 먹을 음식에 유독성 물질을 넣은 30대 여성이 특수상해 혐의로 경찰에...      0   
..                                                 ...    ...   
98   국민의힘 성일종 정책위의장은 1일 김승희 보건복지부 장관 후보자에 대해 “수사가 의...      0   
99   박지원 전 국가정보원장은 윤석열 대통령의 첫 해외순방에 대해 “100점 만점에 80...      0   
100  앞으로 여행을 떠날때 네이버에서 지역 맛집·카페, 명소 등을 일일이 검색해야하는 번...      0   
101  오늘의 줄서기: 온라인 암표 매크로는 필수…시장질서 교란하는 암표상들 정부당국 손 ...      0   
102  ‘닥터 둠’ 루비니 교수 경고 2008년 글로벌 금융 위기를 예측해 대표적인 ‘닥터...      0   

                                                   url  
0    https://n.news.naver.com/mnews/article/023/000...  
1    https://n.news.naver.com/mnews/article/023/000...  
2    https://n.news.naver.com/mnews/article/023/000...  
3    https://n.news.naver.com/mnews/article/023/000...  
4    https://n.news.naver.com/mnews/article/023/000...  
..                                                 ...  
98   https://n.news.naver.com/mnews/article/023/000...  
99   https://n.news.naver.com/mnews/article/023/000...  
100  https://n.news.naver.com/mnews/article/023/000...  
101  https://n.news.naver.com/mnews/article/023/000...  
102  https://n.news.naver.com/mnews/article/023/000...  

[100 rows x 4 columns]

In [4]:
# korean_economy_database = korean_economy_database.dropna()
# korean_economy_database.head(100)

In [5]:
# mail_economy_database = mail_economy_database
# mail_economy_database.head(100)

In [6]:
# midlle_eilbo_database = midlle_eilbo_database.dropna()
# midlle_eilbo_database.head(100)

In [7]:
# money_today_database = money_today_database.dropna()
# money_today_database.head(100)

표본별 뉴스 제목중 하나 부르기

In [8]:
chosun_eilbo_database['title'][0]

'판다는 언제부터 대나무만 먹었을까? 600만년 전 화석 봤더니…'

뉴스 출처 홈페이지 추출하기

In [9]:
chosun_eilbo_database['url'][0]

'https://n.news.naver.com/mnews/article/023/0003701167'

## 깃허브 오픈소스 이용하기

### 토큰화로 바꾸는 파일 부르기

In [10]:
# $ git clone https://github.com/ukairia777/tensorflow-nlp-tutorial.git
# $ git clone https://github.com/haven-jeon/PyKoSpacing.git
# $ git clone https://github.com/ssut/py-hanspell.git
# %pip install soynlp
# %pip install customized_konlpy

In [11]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [12]:
%pip install kss

Note: you may need to restart the kernel to use updated packages.


In [13]:
%pip install konlpy

In [14]:
%pip install soynlp

Note: you may need to restart the kernel to use updated packages.


In [15]:
%pip install customized_konlpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
from tokenization import *

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[Korean Sentence Splitter]: Initializing Pynori...


단어 토큰화1 : ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']
단어 토큰화2 : ['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']
단어 토큰화3 : ["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']
트리뱅크 워드토크나이저 : ['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']
문장 토큰화1 : ['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of 

In [17]:
from text_preprocessing_tools_for_korean_text import *

김철수는극중두인격의사나이이광수역을맡았다.철수는한국유일의태권도전승자를가리는결전의날을앞두고10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다.
1/1 [==============================] - 6s 6s/step
김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.
김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.
맞춤법 틀리면 왜 안돼? 쓰고 싶은 대로 쓰면 되지
김철수는 극 중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연제(김광수 분)를 찾으러 속세로 내려온 인물이다.
김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.
19  1990  52 1 22
오패산터널 총격전 용의자 검거 서울 연합뉴스 경찰 관계자들이 19일 오후 서울 강북구 오패산 터널 인근에서 사제 총기를 발사해 경찰을 살해한 용의자 성모씨를 검거하고 있다 성씨는 검거 당시 서바이벌 게임에서 쓰는 방탄조끼에 헬멧까지 착용한 상태였다 독자제공 영상 캡처 연합뉴스  서울 연합뉴스 김은경 기자 사제 총기로 경찰을 살해한 범인 성모 46 씨는 주도면밀했다  경찰에 따르면 성씨는 19일 오후 강북경찰서 인근 부동산 업소 밖에서 부동산업자 이모 67 씨가 나오기를 기다렸다 이씨와는 평소에도 말다툼을 자주 한 것으로 알려졌다  이씨가 나와 걷기 시작하자 성씨는 따라가면서 미리 준비해온 사제 총기를 이씨에게 발사했다 총알이 빗나가면서 이씨는 도망갔다 그 빗나

c:\Users\user\anaconda3\lib\site-packages\konlpy\tag\_okt.py:17: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


url 홈페이지 BeautifulSoup을이용해서 소스에 있는 내용 부르기

In [18]:
headers = {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"}
response_0 = requests.get(chosun_eilbo_database["url"][0], headers=headers)
soup_0 = BeautifulSoup(response_0.text, 'html.parser')
content_0_data = soup_0.find('div', {"id" : "dic_area"}).get_text()
content_0_data = content_0_data.replace('\n','').replace('\t','')
print(content_0_data)
new_content_0_data = content_0_data.replace(" ", '')

kospacing_new_content_0_data = spacing(new_content_0_data) 
print(kospacing_new_content_0_data)

판다. /픽사베이통통한 몸집과 어울리지 않게 대나무를 주식으로 하는 판다. 이런 판다의 독특한 식성이 최소 600만년 전부터 이어졌을 가능성이 있다는 연구 결과가 나왔다.1일(현지 시각) CNN 등 외신에 따르면 미국 로스앤젤레스 자연사 박물관의 왕 샤오밍 박사 연구팀은 최근 약 600만년 전 자이언트 판다 조상인 아일루락토스(Ailurarctos) 화석을 분석한 결과, 대나무를 잡는 데 쓰이는 ‘가짜 엄지’가 존재했다고 밝혔다.이 화석은 중국 남부 윈난성 자오퉁시의 슈이탕바 지역에서 발굴됐다. 약 600만년 전 살았던 고대 판다 아일루락토스의 것이다. 눈여겨볼 것은 손목 부위에서 발견된 돌출 뼈다. 연구팀은 바로 이 뼈가 자이언트 판다가 가진 여섯 번째 손가락 일명 ‘가짜 엄지’라고 말했다.판다의 가짜 엄지. /뉴시스판다의 가짜 엄지는 대나무를 보다 쉽게 잡을 수 있도록 하는 데 쓰인다. 판다가 초식동물로 진화하는 데 중추적인 역할을 했을 것으로 전문가들은 보고 있다. 그동안 이같은 진화적 적응은 약 15만년 전인 비교적 최근 이뤄진 것으로 여겨져 왔는데, 이번 연구가 무려 600만년을 거슬러 올라간다는 것을 증명해낸 셈이다.화석에서 발견된 가짜 엄지는 현대 판다의 것보다 더 긴 길이의 직선 모양을 하고 있었다. 연구팀은 “가짜 엄지는 대나무를 잡고 뜯어먹을 때는 물론 다음 먹이를 찾아 걸어갈 때 몸무게를 지탱하는 용도로도 쓰이는데, 이 과정에서 긴 뼈가 짧은 갈고리형으로 진화하게 된 것”이라고 분석했다.왕 박사는 “대나무를 먹기 좋게 쪼개기 위해 줄기를 단단히 붙잡는 것은 많은 양의 대나무를 먹는 데 가장 중요한 적응”이라며 “육식성 조상에서 진화해 대나무만 먹는 종으로 바뀐 판다는 많은 장애를 넘어야 했을 것이고 가짜 엄지는 그중 가장 놀라운 진화”라고 설명했다.
1/1 [==============================] - 0s 16ms/step
판다. / 픽사베이통통한 몸집과 어울리지 않게 대나무를 주식으로 하는 판다. 이런 판다의 독특한 식성

In [19]:
print(twitter.morphs(kospacing_new_content_0_data))

['판다', '.', '/', '픽사', '베이', '통통', '한', '몸집', '과', '어울', '리지', '않게', '대나무', '를', '주식', '으로', '하는', '판다', '.', '이런', '판다', '의', '독특', '한', '식성', '이', '최소', '600', '만년', '전부', '터', '이어졌을', '가능성', '이', '있다는', '연구', '결과', '가', '나왔다', '.', '1일', '(', '현지', '시각', ')', 'CNN', '등', '외신', '에', '따르면', '미국', '로스앤젤레스', '자연사', '박물관', '의', '왕샤오밍', '박사', '연구', '팀', '은', '최근', '약', '600', '만년', '전', '자이언트', '판다', '조상', '인', '아', '일루', '락토스', '(', 'A', 'ilurarctos', ')', '화석', '을', '분석', '한', '결과', ',', '대나무', '를', '잡는', '데', '쓰이는', '‘', '가짜', '엄지', '’', '가', '존재', '했다고', '밝혔다', '.', '이', '화석', '은', '중국', '남부', '윈', '난', '성', '자오퉁시', '의', '슈이', '탕바', '지역', '에서', '발굴', '됐다', '.', '약', '600', '만년', '전', '살았던', '고대', '판다', '아', '일루', '락토스', '의', '것', '이다', '.', '눈', '여겨', '볼', '것', '은', '손목', '부위', '에서', '발견', '된', '돌출', '뼈', '다', '.', '연구', '팀', '은', '바로', '이', '뼈', '가', '자이언트', '판다', '가', '가진', '여섯', '번째', '손가락', '일명', '‘', '가짜', '엄지', '’', '라고', '말', '했다', '.', '판다', '의', '가짜', '엄지', '.', '/', '뉴시스', '

In [20]:
words_data = twitter.morphs(content_0_data)

표제어 제거하기 

In [21]:
from stemming_lemmatization import *

표제어 추출 전 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


표제어 추출 후 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']
die
watch
have
어간 추출 전 : ['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']
어간 추출 후 : ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']
어간 추출 전 : ['formalize', 'allowance', 'electricical']
어간 추출 후 : ['formal', 'allow', 'electric']
어간 추출 전 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'w

In [22]:

# for word in words_data:
#     print(lemmatizer.lemmatize(word))
#     print()

뉴스 내용항목 중 한국어 불용어 제거하기

In [23]:
from remove_stopwords import *

불용어 개수 : 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]
불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [24]:
with open("C:\\Users\\user\\Documents\\github\\bigdata_thunder\\bigdata2\\korean_stopwords.txt", "r", encoding="UTF-8") as stopwords:
    stopwords_list = stopwords.read().split('\n')
print('불용어 제거 전 :',words_data) 
print()
print('불용어 제거 후 :',korean_change_no_stop_words(words_data, stopwords_list))

불용어 제거 전 : ['판다', '.', '/', '픽사', '베이', '통통', '한', '몸집', '과', '어울', '리지', '않게', '대나무', '를', '주식', '으로', '하는', '판다', '.', '이런', '판다', '의', '독특', '한', '식성', '이', '최소', '600', '만년', '전부', '터', '이어졌을', '가능성', '이', '있다는', '연구', '결과', '가', '나왔다', '.', '1일', '(', '현지', '시각', ')', 'CNN', '등', '외신', '에', '따르면', '미국', '로스앤젤레스', '자연사', '박물관', '의', '왕', '샤오밍', '박사', '연구', '팀', '은', '최근', '약', '600', '만년', '전', '자이언트', '판다', '조상', '인', '아', '일루', '락토스', '(', 'Ailurarctos', ')', '화석', '을', '분석', '한', '결과', ',', '대나무', '를', '잡는', '데', '쓰이는', '‘', '가짜', '엄지', '’', '가', '존재', '했다고', '밝혔다', '.', '이', '화석', '은', '중국', '남부', '윈난성', '자오퉁시', '의', '슈이탕바', '지역', '에서', '발굴', '됐다', '.', '약', '600', '만년', '전', '살았던', '고대', '판다', '아', '일루', '락토스', '의', '것', '이다', '.', '눈', '여겨', '볼', '것', '은', '손목', '부위', '에서', '발견', '된', '돌출', '뼈', '다', '.', '연구', '팀', '은', '바로', '이', '뼈', '가', '자이언트', '판다', '가', '가진', '여섯', '번째', '손가락', '일명', '‘', '가짜', '엄지', '’', '라고', '말', '했다', '.', '판다', '의', '가짜', '엄지', '.', '/', '뉴시스', '판

In [25]:
new_content_1 ='' 
for i in korean_change_no_stop_words(words_data, stopwords_list):
    new_content_1 += i
print(new_content_1)

판다./픽사베이통통한몸집어울리지않게대나무주식하는판다.판다독특한식성최소600만년터이어졌을가능성있다는연구결과나왔다.1일(현지)CNN외신따르면미국로스앤젤레스자연사박물관왕샤오밍박사연구팀은최근약600만년전자이언트판다조상인일루락토스(Ailurarctos)화석분석한결과,대나무잡는데쓰이는‘가짜엄지’존재했다고밝혔다.화석은중국남부윈난성자오퉁시슈이탕바지역발굴됐다.약600만년전살았던고대판다일루락토스이다.눈여겨볼은손목부위발견된돌출뼈다.연구팀은뼈자이언트판다가진번째손가락일명‘가짜엄지’라고말했다.판다가짜엄지./뉴시스판다가짜엄지는대나무보다쉽게잡수있도록하는데쓰인다.판다초식동물진화하는데중추적인역할했을전문가들은보고.그동안같은진화적적응은약15만년전인비교적최근이뤄진여겨져왔는데,연구무려600만년거슬러올라간다는증명해낸셈이다.화석발견된가짜엄지는현대판다보다더긴길이직선모양하고있었다.연구팀은“가짜엄지는대나무잡고뜯어먹을는먹이찾아걸어갈몸무게지탱하는용도도쓰이는데,과정긴뼈짧은갈고리형진화하게된”이라고분석했다.왕박사는“대나무먹기좋게쪼개기위해줄기단단히붙잡는은많은양대나무먹는데가장중요한적응”라며“육식성조상진화해대나무만먹는종바뀐판다는많은장애넘어야했을이고가짜엄지는그중가장놀라운진화”라고설명했다.


문장 텍스트 정규화하기

In [26]:
from regular_expression import *

Regular expression   A regular expression  regex or regexp     sometimes called a rational expression        is  in theoretical computer science and formal language theory  a sequence of characters that define a search pattern 
['Don', 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'Mr', 'Jone', 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']
["Don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name,', 'Mr.', "Jone's", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


In [27]:
tokenizer3_content_1 = RegexpTokenizer('[A-Za-z0-9ㄱ-ㅎ/()]+', gaps=True)
# tokenizer3_content_2 = RegexpTokenizer('')
print(tokenizer3_content_1.tokenize(new_content_1))

['판다.', '픽사베이통통한몸집어울리지않게대나무주식하는판다.판다독특한식성최소', '만년터이어졌을가능성있다는연구결과나왔다.', '일', '현지', '외신따르면미국로스앤젤레스자연사박물관왕샤오밍박사연구팀은최근약', '만년전자이언트판다조상인일루락토스', '화석분석한결과,대나무잡는데쓰이는‘가짜엄지’존재했다고밝혔다.화석은중국남부윈난성자오퉁시슈이탕바지역발굴됐다.약', '만년전살았던고대판다일루락토스이다.눈여겨볼은손목부위발견된돌출뼈다.연구팀은뼈자이언트판다가진번째손가락일명‘가짜엄지’라고말했다.판다가짜엄지.', '뉴시스판다가짜엄지는대나무보다쉽게잡수있도록하는데쓰인다.판다초식동물진화하는데중추적인역할했을전문가들은보고.그동안같은진화적적응은약', '만년전인비교적최근이뤄진여겨져왔는데,연구무려', '만년거슬러올라간다는증명해낸셈이다.화석발견된가짜엄지는현대판다보다더긴길이직선모양하고있었다.연구팀은“가짜엄지는대나무잡고뜯어먹을는먹이찾아걸어갈몸무게지탱하는용도도쓰이는데,과정긴뼈짧은갈고리형진화하게된”이라고분석했다.왕박사는“대나무먹기좋게쪼개기위해줄기단단히붙잡는은많은양대나무먹는데가장중요한적응”라며“육식성조상진화해대나무만먹는종바뀐판다는많은장애넘어야했을이고가짜엄지는그중가장놀라운진화”라고설명했다.']


In [28]:
regular_expression_sentence = ''
for expression in tokenizer3_content_1.tokenize(new_content_1):
    regular_expression_sentence += expression
print(regular_expression_sentence)

판다.픽사베이통통한몸집어울리지않게대나무주식하는판다.판다독특한식성최소만년터이어졌을가능성있다는연구결과나왔다.일현지외신따르면미국로스앤젤레스자연사박물관왕샤오밍박사연구팀은최근약만년전자이언트판다조상인일루락토스화석분석한결과,대나무잡는데쓰이는‘가짜엄지’존재했다고밝혔다.화석은중국남부윈난성자오퉁시슈이탕바지역발굴됐다.약만년전살았던고대판다일루락토스이다.눈여겨볼은손목부위발견된돌출뼈다.연구팀은뼈자이언트판다가진번째손가락일명‘가짜엄지’라고말했다.판다가짜엄지.뉴시스판다가짜엄지는대나무보다쉽게잡수있도록하는데쓰인다.판다초식동물진화하는데중추적인역할했을전문가들은보고.그동안같은진화적적응은약만년전인비교적최근이뤄진여겨져왔는데,연구무려만년거슬러올라간다는증명해낸셈이다.화석발견된가짜엄지는현대판다보다더긴길이직선모양하고있었다.연구팀은“가짜엄지는대나무잡고뜯어먹을는먹이찾아걸어갈몸무게지탱하는용도도쓰이는데,과정긴뼈짧은갈고리형진화하게된”이라고분석했다.왕박사는“대나무먹기좋게쪼개기위해줄기단단히붙잡는은많은양대나무먹는데가장중요한적응”라며“육식성조상진화해대나무만먹는종바뀐판다는많은장애넘어야했을이고가짜엄지는그중가장놀라운진화”라고설명했다.


In [29]:
from integer_encoding import *

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']
[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]
{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}
8
[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good'

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [30]:

vocab = {}
preprocessed_sentences = []

for sentence in sent_tokenize(regular_expression_sentence):
    # 단어 토큰화
    tokenized_sentence = twitter.nouns(sentence)

    for word in tokenized_sentence: 
        if len(word) > 2: 
            result.append(word)
            if word not in vocab:
                vocab[word] = 0 
            vocab[word] += 1
    preprocessed_sentences.append(result) 
print(preprocessed_sentences)   

[['barber', 'went', 'huge', 'mountain', '대나무', '가능성', '로스앤젤레스', '자연사', '박물관', '왕샤오밍', '자이언트판다', '락토스', '대나무', '윈난성', '자오퉁시', '슈이탕바', '락토스', '자이언트판다', '손가락', '뉴시스', '대나무', '초식동물', '전문가', '그동안', '년거슬러올', '대나무', '몸무게', '갈고리', '대나무', '대나무', '육식성', '대나무']]


In [31]:
print(vocab)

{'대나무': 7, '가능성': 1, '로스앤젤레스': 1, '자연사': 1, '박물관': 1, '왕샤오밍': 1, '자이언트판다': 2, '락토스': 2, '윈난성': 1, '자오퉁시': 1, '슈이탕바': 1, '손가락': 1, '뉴시스': 1, '초식동물': 1, '전문가': 1, '그동안': 1, '년거슬러올': 1, '몸무게': 1, '갈고리': 1, '육식성': 1}


In [32]:
all_words_list = sum(preprocessed_sentences, [])
print(all_words_list)

['barber', 'went', 'huge', 'mountain', '대나무', '가능성', '로스앤젤레스', '자연사', '박물관', '왕샤오밍', '자이언트판다', '락토스', '대나무', '윈난성', '자오퉁시', '슈이탕바', '락토스', '자이언트판다', '손가락', '뉴시스', '대나무', '초식동물', '전문가', '그동안', '년거슬러올', '대나무', '몸무게', '갈고리', '대나무', '대나무', '육식성', '대나무']


In [33]:
vocab = Counter(all_words_list)
print(vocab)

Counter({'대나무': 7, '자이언트판다': 2, '락토스': 2, 'barber': 1, 'went': 1, 'huge': 1, 'mountain': 1, '가능성': 1, '로스앤젤레스': 1, '자연사': 1, '박물관': 1, '왕샤오밍': 1, '윈난성': 1, '자오퉁시': 1, '슈이탕바': 1, '손가락': 1, '뉴시스': 1, '초식동물': 1, '전문가': 1, '그동안': 1, '년거슬러올': 1, '몸무게': 1, '갈고리': 1, '육식성': 1})


In [34]:
print(vocab["판다"])

0


In [35]:
vocab_size = 10
vocab = vocab.most_common(vocab_size) # 등장 빈도수가 높은 상위 5개의 단어만 저장
print(vocab)

word_to_index = {}
i = 0
for (word, frequency) in vocab :
    i = i + 1
    word_to_index[word] = i
    
print(word_to_index)

[('대나무', 7), ('자이언트판다', 2), ('락토스', 2), ('barber', 1), ('went', 1), ('huge', 1), ('mountain', 1), ('가능성', 1), ('로스앤젤레스', 1), ('자연사', 1)]
{'대나무': 1, '자이언트판다': 2, '락토스': 3, 'barber': 4, 'went': 5, 'huge': 6, 'mountain': 7, '가능성': 8, '로스앤젤레스': 9, '자연사': 10}


In [36]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
print(tokenizer.word_index)
print()
print(tokenizer.word_counts)
print()
print(tokenizer.texts_to_sequences(preprocessed_sentences))

{'대나무': 1, '자이언트판다': 2, '락토스': 3, 'barber': 4, 'went': 5, 'huge': 6, 'mountain': 7, '가능성': 8, '로스앤젤레스': 9, '자연사': 10, '박물관': 11, '왕샤오밍': 12, '윈난성': 13, '자오퉁시': 14, '슈이탕바': 15, '손가락': 16, '뉴시스': 17, '초식동물': 18, '전문가': 19, '그동안': 20, '년거슬러올': 21, '몸무게': 22, '갈고리': 23, '육식성': 24}

OrderedDict([('barber', 1), ('went', 1), ('huge', 1), ('mountain', 1), ('대나무', 7), ('가능성', 1), ('로스앤젤레스', 1), ('자연사', 1), ('박물관', 1), ('왕샤오밍', 1), ('자이언트판다', 2), ('락토스', 2), ('윈난성', 1), ('자오퉁시', 1), ('슈이탕바', 1), ('손가락', 1), ('뉴시스', 1), ('초식동물', 1), ('전문가', 1), ('그동안', 1), ('년거슬러올', 1), ('몸무게', 1), ('갈고리', 1), ('육식성', 1)])

[[4, 5, 6, 7, 1, 8, 9, 10, 11, 12, 2, 3, 1, 13, 14, 15, 3, 2, 16, 17, 1, 18, 19, 20, 21, 1, 22, 23, 1, 1, 24, 1]]


In [37]:
vocab_size = 10
tokenizer = Tokenizer(num_words = vocab_size + 1) # 상위 10개 단어만 사용
tokenizer.fit_on_texts(preprocessed_sentences)

print(tokenizer.word_index)
print()
print(tokenizer.word_counts)
print()
print(tokenizer.texts_to_sequences(preprocessed_sentences))
print()
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)

{'대나무': 1, '자이언트판다': 2, '락토스': 3, 'barber': 4, 'went': 5, 'huge': 6, 'mountain': 7, '가능성': 8, '로스앤젤레스': 9, '자연사': 10, '박물관': 11, '왕샤오밍': 12, '윈난성': 13, '자오퉁시': 14, '슈이탕바': 15, '손가락': 16, '뉴시스': 17, '초식동물': 18, '전문가': 19, '그동안': 20, '년거슬러올': 21, '몸무게': 22, '갈고리': 23, '육식성': 24}

OrderedDict([('barber', 1), ('went', 1), ('huge', 1), ('mountain', 1), ('대나무', 7), ('가능성', 1), ('로스앤젤레스', 1), ('자연사', 1), ('박물관', 1), ('왕샤오밍', 1), ('자이언트판다', 2), ('락토스', 2), ('윈난성', 1), ('자오퉁시', 1), ('슈이탕바', 1), ('손가락', 1), ('뉴시스', 1), ('초식동물', 1), ('전문가', 1), ('그동안', 1), ('년거슬러올', 1), ('몸무게', 1), ('갈고리', 1), ('육식성', 1)])

[[4, 5, 6, 7, 1, 8, 9, 10, 2, 3, 1, 3, 2, 1, 1, 1, 1, 1]]



In [38]:
words_frequency = [word for word, index in tokenizer.word_index.items() if index >= vocab_size + 1] # 인덱스가 5 초과인 단어 제거
for word in words_frequency:
    del tokenizer.word_index[word] # 해당 단어에 대한 인덱스 정보를 삭제
    del tokenizer.word_counts[word] # 해당 단어에 대한 카운트 정보를 삭제

print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preprocessed_sentences))

{'대나무': 1, '자이언트판다': 2, '락토스': 3, 'barber': 4, 'went': 5, 'huge': 6, 'mountain': 7, '가능성': 8, '로스앤젤레스': 9, '자연사': 10}
OrderedDict([('barber', 1), ('went', 1), ('huge', 1), ('mountain', 1), ('대나무', 7), ('가능성', 1), ('로스앤젤레스', 1), ('자연사', 1), ('자이언트판다', 2), ('락토스', 2)])
[[4, 5, 6, 7, 1, 8, 9, 10, 2, 3, 1, 3, 2, 1, 1, 1, 1, 1]]


In [39]:
%pip install tensorflow

In [40]:
from one_encoding import *

['나', '는', '자연어', '처리', '를', '배운다']
단어 집합 : {'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}
단어 집합 : {'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}
[2, 5, 1, 6, 3, 7]
[2, 5, 1, 6, 3, 7]
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [41]:
tokens = twitter.morphs(chosun_eilbo_database['title'][0])
print(tokens)
word_to_index = {word : index for index, word in enumerate(tokens)}
for i in tokens:
    print(one_hot_encoding(i, word_to_index=word_to_index))

['판다', '는', '언제', '부터', '대나무', '만', '먹었을까', '?', '600', '만년', '전', '화석', '봤', '더니', '…']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


In [42]:
from padding import *

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]
7
[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]
14


In [43]:
tokenizer = Tokenizer()
# fit_on_texts()안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성.
tokenizer.fit_on_texts(preprocessed_sentences)

In [44]:
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [45]:
padded_1 = pad_sequences(encoded)
print(padded_1)

[[ 0  0  0  0  0  1  5]
 [ 0  0  0  0  1  8  5]
 [ 0  0  0  0  1  3  5]
 [ 0  0  0  0  0  9  2]
 [ 0  0  0  2  4  3  2]
 [ 0  0  0  0  0  3  2]
 [ 0  0  0  0  1  4  6]
 [ 0  0  0  0  1  4  6]
 [ 0  0  0  0  1  4  2]
 [ 7  7  3  2 10  1 11]
 [ 0  0  0  1 12  3 13]]


In [46]:
padded_2 = pad_sequences(encoded, padding='post')
padded_2

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [47]:
padded_3 = pad_sequences(encoded, padding='post', maxlen=5)
print(padded_3)
print()
padded_4 = pad_sequences(encoded, padding='post', truncating='post')
print(padded_4)
print()
padded_5 = pad_sequences(encoded, padding='post', truncating='post', maxlen=5)
print(padded_5)
print()
# 단어 집합의 크기보다 1 큰 숫자를 사용
last_value = len(tokenizer.word_index) + 1
print(last_value)
print()
padded_6 = pad_sequences(encoded, padding='post', value=last_value)
print(padded_6)

[[ 1  5  0  0  0]
 [ 1  8  5  0  0]
 [ 1  3  5  0  0]
 [ 9  2  0  0  0]
 [ 2  4  3  2  0]
 [ 3  2  0  0  0]
 [ 1  4  6  0  0]
 [ 1  4  6  0  0]
 [ 1  4  2  0  0]
 [ 3  2 10  1 11]
 [ 1 12  3 13  0]]

[[ 1  5  0  0  0  0  0]
 [ 1  8  5  0  0  0  0]
 [ 1  3  5  0  0  0  0]
 [ 9  2  0  0  0  0  0]
 [ 2  4  3  2  0  0  0]
 [ 3  2  0  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  2  0  0  0  0]
 [ 7  7  3  2 10  1 11]
 [ 1 12  3 13  0  0  0]]

[[ 1  5  0  0  0]
 [ 1  8  5  0  0]
 [ 1  3  5  0  0]
 [ 9  2  0  0  0]
 [ 2  4  3  2  0]
 [ 3  2  0  0  0]
 [ 1  4  6  0  0]
 [ 1  4  6  0  0]
 [ 1  4  2  0  0]
 [ 7  7  3  2 10]
 [ 1 12  3 13  0]]

14

[[ 1  5 14 14 14 14 14]
 [ 1  8  5 14 14 14 14]
 [ 1  3  5 14 14 14 14]
 [ 9  2 14 14 14 14 14]
 [ 2  4  3  2 14 14 14]
 [ 3  2 14 14 14 14 14]
 [ 1  4  6 14 14 14 14]
 [ 1  4  6 14 14 14 14]
 [ 1  4  2 14 14 14 14]
 [ 7  7  3  2 10  1 11]
 [ 1 12  3 13 14 14 14]]


## TF-IDF를 이용하여 벡터화하기

### bag_of_words 구현하기

In [48]:
from kiwipiepy import Kiwi

In [49]:
from bag_of_words import *

vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}
bag of words vector : [1, 2, 1, 1, 2, 1, 1, 1, 1, 1]
vocabulary : {'소비자': 0, '는': 1, '주로': 2, '소비': 3, '하는': 4, '상품': 5, '을': 6, '기준': 7, '으로': 8, '물가상승률': 9, '느낀다': 10}
bag of words vector : [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1]
정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다. 소비자는 주로 소비하는 상품을 기준으로 물가상승률을 느낀다.
vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9, '는': 10, '주로': 11, '소비': 12, '상품': 13, '을': 14, '기준': 15, '으로': 16, '느낀다': 17}
bag of words vector : [1, 2, 1, 2, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1]
bag of words vector : [[1 1 2 1 2 1]]
vocabulary : {'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}
bag of words vector : [[1 1 1 1 1]]
vocabulary : {'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}
bag of words vector : [[1 1 1]]
vocabulary : {'family': 0, 'important': 1, 'thing': 2}
bag of wo

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [50]:
kiwi = Kiwi()
spacing = Spacing()
kospacing_sent = spacing(regular_expression_sentence) 

kospacing_sent

1/1 [==============================] - 0s 33ms/step


'판다.픽사 베이통통한 몸집 어울리지 않게 대나무 주식하는 판다. 판다독특한 식성 최소 만년 터이어졌을 가능성 있다는 연구 결과 나왔다. 일 현지 외신 따르면 미국 로스앤젤레스 자연사박물관 왕샤오밍 박사 연구팀은 최근 약 만년 전자이언트 판다 조상인 일루락토스 화 석 분석한 결과, 대나무 잡는데 쓰이는 ‘가짜 엄지’ 존재했다고 밝혔다. 화석은 중국 남부 윈난성 자오퉁시 슈이 탕바지역 발굴됐다.약 만년 전 살았던 고대 판다일루락토스이다. 눈여겨볼은 손목 부위 발견된 돌출뼈다. 연구팀은 뼈 자이언트 판다가 진번째 손가락 일명 ‘가짜 엄지’라고 말했다. 판다가짜 엄지.뉴시스판다가짜 엄지는 대나무보다 쉽게 잡수 있도록 하는 데 쓰인다. 판다초식 동물 진화하는데 중추적인 역할했을 전문가들은 보고. 그동안 같은 진화적 적응은 약 만년 전 인 비교적 최근 이뤄진 여겨져 왔는데, 연구 무려 만년 거슬러 올라간다는 증명해낸 셈이다. 화석 발견된 가짜 엄지는 현대판다보다 더 긴 길이 직선 모양하고 있었다.연구팀은 “가짜 엄지는 대나무 잡고 뜯어먹을는 먹이 찾아 걸어갈 몸무게 지탱하는 용도도 쓰이는데, 과정 긴 뼈 짧은 갈고리형 진화하게 된”이라고 분석했다. 왕 박사는 “대나무 먹기 좋게 쪼개기 위해 줄기 단단히 붙잡는 은 많은 양대나무 먹는데 가장 중요한 적응”라며 “육식성 조상 진화해대나무만 먹는 종 바뀐 판다는 많은 장애 넘어야 했을 이고 가짜 엄지는 그 중 가장 놀라운 진화”라고 설명했다.'

In [51]:
vocab, bow = build_bag_of_words(kospacing_sent)
print(vocab)
print(bow)

{'판다': 0, '픽사': 1, '베이': 2, '통통한': 3, '몸집': 4, '어울리지': 5, '않게': 6, '대나무': 7, '주식': 8, '하는': 9, '독특한': 10, '식성': 11, '최소': 12, '만년': 13, '터': 14, '이어졌을': 15, '가능성': 16, '있다는': 17, '연구': 18, '결과': 19, '나왔다': 20, '일': 21, '현지': 22, '외신': 23, '따르면': 24, '미국': 25, '로스앤젤레스': 26, '자연사': 27, '박물관': 28, '왕샤오밍': 29, '박사': 30, '연': 31, '구': 32, '팀': 33, '은': 34, '최근': 35, '약': 36, '전': 37, '자이언트': 38, '조상': 39, '인': 40, '일루': 41, '락토스': 42, '화': 43, '석': 44, '분석': 45, '한': 46, ',': 47, '잡는데': 48, '쓰이는': 49, '‘': 50, '가짜': 51, '엄지': 52, '’': 53, '존재': 54, '했다고': 55, '밝혔다': 56, '화석': 57, '중국': 58, '남부': 59, '윈난성': 60, '자오퉁시': 61, '슈이': 62, '탕바': 63, '지역': 64, '발굴': 65, '됐다': 66, '살았던': 67, '고대': 68, '이다': 69, '눈': 70, '여겨': 71, '볼': 72, '손목': 73, '부위': 74, '발견': 75, '된': 76, '돌출': 77, '뼈': 78, '다': 79, '가': 80, '진번': 81, '째': 82, '손가락': 83, '일명': 84, '라고': 85, '말': 86, '했다': 87, '뉴시스': 88, '는': 89, '보다': 90, '쉽게': 91, '잡수': 92, '있도록': 93, '데': 94, '쓰인다': 95, '초식': 96, '동물': 97, '진화': 98, '하는데': 99,

In [52]:
from tf_idf import *

단어장의 크기 : 9
['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']
[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}
[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [53]:
kospacing_sent 
print(kospacing_sent)

판다.픽사 베이통통한 몸집 어울리지 않게 대나무 주식하는 판다. 판다독특한 식성 최소 만년 터이어졌을 가능성 있다는 연구 결과 나왔다. 일 현지 외신 따르면 미국 로스앤젤레스 자연사박물관 왕샤오밍 박사 연구팀은 최근 약 만년 전자이언트 판다 조상인 일루락토스 화 석 분석한 결과, 대나무 잡는데 쓰이는 ‘가짜 엄지’ 존재했다고 밝혔다. 화석은 중국 남부 윈난성 자오퉁시 슈이 탕바지역 발굴됐다.약 만년 전 살았던 고대 판다일루락토스이다. 눈여겨볼은 손목 부위 발견된 돌출뼈다. 연구팀은 뼈 자이언트 판다가 진번째 손가락 일명 ‘가짜 엄지’라고 말했다. 판다가짜 엄지.뉴시스판다가짜 엄지는 대나무보다 쉽게 잡수 있도록 하는 데 쓰인다. 판다초식 동물 진화하는데 중추적인 역할했을 전문가들은 보고. 그동안 같은 진화적 적응은 약 만년 전 인 비교적 최근 이뤄진 여겨져 왔는데, 연구 무려 만년 거슬러 올라간다는 증명해낸 셈이다. 화석 발견된 가짜 엄지는 현대판다보다 더 긴 길이 직선 모양하고 있었다.연구팀은 “가짜 엄지는 대나무 잡고 뜯어먹을는 먹이 찾아 걸어갈 몸무게 지탱하는 용도도 쓰이는데, 과정 긴 뼈 짧은 갈고리형 진화하게 된”이라고 분석했다. 왕 박사는 “대나무 먹기 좋게 쪼개기 위해 줄기 단단히 붙잡는 은 많은 양대나무 먹는데 가장 중요한 적응”라며 “육식성 조상 진화해대나무만 먹는 종 바뀐 판다는 많은 장애 넘어야 했을 이고 가짜 엄지는 그 중 가장 놀라운 진화”라고 설명했다.


In [54]:
title = chosun_eilbo_database['title'][0]
title = spacing(title)
title

1/1 [==============================] - 0s 17ms/step


'판다는 언제부터 대나무만 먹었을까? 600만년 전 화석 봤더니…'

In [55]:
kospacing_sent_list = []
list1 = kospacing_sent.split('.')
for i in list1:
    i_list1 = i.split(',')
    for i_2 in i_list1:
        kospacing_sent_list.append(i_2.strip())
print(kospacing_sent_list)

['판다', '픽사 베이통통한 몸집 어울리지 않게 대나무 주식하는 판다', '판다독특한 식성 최소 만년 터이어졌을 가능성 있다는 연구 결과 나왔다', '일 현지 외신 따르면 미국 로스앤젤레스 자연사박물관 왕샤오밍 박사 연구팀은 최근 약 만년 전자이언트 판다 조상인 일루락토스 화 석 분석한 결과', '대나무 잡는데 쓰이는 ‘가짜 엄지’ 존재했다고 밝혔다', '화석은 중국 남부 윈난성 자오퉁시 슈이 탕바지역 발굴됐다', '약 만년 전 살았던 고대 판다일루락토스이다', '눈여겨볼은 손목 부위 발견된 돌출뼈다', '연구팀은 뼈 자이언트 판다가 진번째 손가락 일명 ‘가짜 엄지’라고 말했다', '판다가짜 엄지', '뉴시스판다가짜 엄지는 대나무보다 쉽게 잡수 있도록 하는 데 쓰인다', '판다초식 동물 진화하는데 중추적인 역할했을 전문가들은 보고', '그동안 같은 진화적 적응은 약 만년 전 인 비교적 최근 이뤄진 여겨져 왔는데', '연구 무려 만년 거슬러 올라간다는 증명해낸 셈이다', '화석 발견된 가짜 엄지는 현대판다보다 더 긴 길이 직선 모양하고 있었다', '연구팀은 “가짜 엄지는 대나무 잡고 뜯어먹을는 먹이 찾아 걸어갈 몸무게 지탱하는 용도도 쓰이는데', '과정 긴 뼈 짧은 갈고리형 진화하게 된”이라고 분석했다', '왕 박사는 “대나무 먹기 좋게 쪼개기 위해 줄기 단단히 붙잡는 은 많은 양대나무 먹는데 가장 중요한 적응”라며 “육식성 조상 진화해대나무만 먹는 종 바뀐 판다는 많은 장애 넘어야 했을 이고 가짜 엄지는 그 중 가장 놀라운 진화”라고 설명했다', '']


In [56]:
def extract_noun_from_kiwi_analyzed(comment):
    temp_sentence = kiwi.analyze(comment)
    noun_list = [token.form for token in temp_sentence[0][0] if re.match('N', token.tag)]
    return noun_list

In [57]:
content_noun = []
for content in kospacing_sent_list:
    for noun in extract_noun_from_kiwi_analyzed(content):
        if len(noun) < 2:
            continue
        else:
            content_noun.append(noun)
content_noun = list(set(content_noun))

In [58]:
kospacing_title_list = []
list2 = title.split('.')
for i in list2:
    i_list1 = i.split(',')
    for i_2 in i_list1:
        kospacing_title_list.append(i_2.strip())
print(kospacing_title_list)

['판다는 언제부터 대나무만 먹었을까? 600만년 전 화석 봤더니…']


In [59]:
title_noun = []
for title in kospacing_title_list:
    for noun in extract_noun_from_kiwi_analyzed(title):
        if len(noun) < 2:
            continue
        else:
            title_noun.append(noun)
title_noun = list(set(content_noun))

In [60]:
vocab = list(set(content_noun+title_noun))
vocab.sort()
print('단어장의 크기 :', len(vocab))
print(vocab)

단어장의 크기 : 66
['가능', '가짜', '갈고리', '결과', '고대', '과정', '그동안', '나무', '남부', '뉴시스', '대나무', '독특', '돌출', '동물', '락토스', '로스앤젤레스', '만년', '먹이', '모양', '몸무게', '몸집', '미국', '박물관', '박사', '발견', '발굴', '베이', '부위', '분석', '설명', '손가락', '손목', '슈이', '식성', '엄지', '역할', '연구', '왕샤오밍', '외신', '용도', '윈난성', '육식성', '자연사', '자오퉁시', '자이언트', '장애', '적응', '전문가', '조상', '존재', '주식', '줄기', '중국', '중추', '증명', '지역', '지탱', '직선', '진화', '초식', '최소', '탕바', '픽사', '현대판', '현지', '화석']


In [61]:
N = len(kospacing_sent_list)
title_N = len(kospacing_title_list)
print(N)
print(title_N)

19
1


In [62]:
result = []

# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
  result.append([])
  d = kospacing_sent_list[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tf(t, d))
        
content_tf_ = pd.DataFrame(result, columns = vocab)

In [63]:
content_tf_

가능  가짜  갈고리  결과  고대  과정  그동안  나무  남부  뉴시스  ...  지탱  직선  진화  초식  최소  탕바  \
0    0   0    0   0   0   0    0   0   0    0  ...   0   0   0   0   0   0   
1    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
2    1   0    0   1   0   0    0   0   0    0  ...   0   0   0   0   1   0   
3    0   0    0   1   0   0    0   0   0    0  ...   0   0   0   0   0   0   
4    0   1    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
5    0   0    0   0   0   0    0   0   1    0  ...   0   0   0   0   0   1   
6    0   0    0   0   1   0    0   0   0    0  ...   0   0   0   0   0   0   
7    0   0    0   0   0   0    0   0   0    0  ...   0   0   0   0   0   0   
8    0   1    0   0   0   0    0   0   0    0  ...   0   0   0   0   0   0   
9    0   1    0   0   0   0    0   0   0    0  ...   0   0   0   0   0   0   
10   0   1    0   0   0   0    0   1   0    1  ...   0   0   0   0   0   0   
11   0   0    0   0   0   0    0   0   0    0  ...   0   0   1   1   0   0   
12   0   0    0   0   0   0    1   0   0    0  ...   0   0   1   0   0   0   
13   0   0    0   0   0   0    0   0   0    0  ...   0   0   0   0   0   0   
14   0   1    0   0   0   0    0   0   0    0  ...   0   1   0   0   0   0   
15   0   1    0   0   0   0    0   1   0    0  ...   1   0   0   0   0   0   
16   0   0    1   0   0   1    0   0   0    0  ...   0   0   1   0   0   0   
17   0   1    0   0   0   0    0   3   0    0  ...   0   0   2   0   0   0   
18   0   0    0   0   0   0    0   0   0    0  ...   0   0   0   0   0   0   

    픽사  현대판  현지  화석  
0    0    0   0   0  
1    1    0   0   0  
2    0    0   0   0  
3    0    0   1   0  
4    0    0   0   0  
5    0    0   0   1  
6    0    0   0   0  
7    0    0   0   0  
8    0    0   0   0  
9    0    0   0   0  
10   0    0   0   0  
11   0    0   0   0  
12   0    0   0   0  
13   0    0   0   0  
14   0    1   0   1  
15   0    0   0   0  
16   0    0   0   0  
17   0    0   0   0  
18   0    0   0   0  

[19 rows x 66 columns]

In [64]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))

content_idf_ = pd.DataFrame(result, index=vocab, columns=["IDF"])
content_idf_

IDF
가능   1.386294
가짜   1.386294
갈고리  1.386294
결과   1.386294
고대   1.386294
..        ...
탕바   1.386294
픽사   1.386294
현대판  1.386294
현지   1.386294
화석   1.386294

[66 rows x 1 columns]

In [65]:
result = []
for i in range(N):
  result.append([])
  d = kospacing_sent_list[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tfidf(t,d))

content_tfidf_ = pd.DataFrame(result, columns = vocab)
content_tfidf_

가능        가짜       갈고리        결과        고대        과정       그동안  \
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   1.386294  0.000000  0.000000  1.386294  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  1.386294  0.000000  0.000000  0.000000   
4   0.000000  1.386294  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  0.000000  1.386294  0.000000  0.000000   
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000  1.386294  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.000000  1.386294  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.000000  1.386294  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.386294   
13  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
14  0.000000  1.386294  0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.000000  1.386294  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.000000  0.000000  1.386294  0.000000  0.000000  1.386294  0.000000   
17  0.000000  1.386294  0.000000  0.000000  0.000000  0.000000  0.000000   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          나무        남부       뉴시스  ...        지탱        직선        진화        초식  \
0   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
1   1.386294  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
4   1.386294  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
5   0.000000  1.386294  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
10  1.386294  0.000000  1.386294  ...  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.386294  1.386294   
12  0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.386294  0.000000   
13  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
14  0.000000  0.000000  0.000000  ...  0.000000  1.386294  0.000000  0.000000   
15  1.386294  0.000000  0.000000  ...  1.386294  0.000000  0.000000  0.000000   
16  0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.386294  0.000000   
17  4.158883  0.000000  0.000000  ...  0.000000  0.000000  2.772589  0.000000   
18  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

          최소        탕바        픽사       현대판        현지        화석  
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1   0.000000  0.000000  1.386294  0.000000  0.000000  0.000000  
2   1.386294  0.000000  0.000000  0.000000  0.000000  0.000000  
3   0.000000  0.000000  0.000000  0.000000  1.386294  0.000000  
4   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
5   0.000000  1.386294  0.000000  0.000000  0.000000  1.386294  
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
8   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
9   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
10  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
11  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
12  0.000000  0.000000 

In [66]:
result = []


# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
  result.append([])
  d = kospacing_title_list[0]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tf(t, d))
        
title_tf_ = pd.DataFrame(result, columns = vocab)

In [67]:
title_tf_

가능  가짜  갈고리  결과  고대  과정  그동안  나무  남부  뉴시스  ...  지탱  직선  진화  초식  최소  탕바  \
0    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
1    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
2    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
3    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
4    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
5    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
6    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
7    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
8    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
9    0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
10   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
11   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
12   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
13   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
14   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
15   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
16   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
17   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   
18   0   0    0   0   0   0    0   1   0    0  ...   0   0   0   0   0   0   

    픽사  현대판  현지  화석  
0    0    0   0   1  
1    0    0   0   1  
2    0    0   0   1  
3    0    0   0   1  
4    0    0   0   1  
5    0    0   0   1  
6    0    0   0   1  
7    0    0   0   1  
8    0    0   0   1  
9    0    0   0   1  
10   0    0   0   1  
11   0    0   0   1  
12   0    0   0   1  
13   0    0   0   1  
14   0    0   0   1  
15   0    0   0   1  
16   0    0   0   1  
17   0    0   0   1  
18   0    0   0   1  

[19 rows x 66 columns]

In [68]:
title_tf_.values

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [69]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))

title_idf_ = pd.DataFrame(result, index=vocab, columns=["IDF"])
title_idf_

IDF
가능   1.386294
가짜   1.386294
갈고리  1.386294
결과   1.386294
고대   1.386294
..        ...
탕바   1.386294
픽사   1.386294
현대판  1.386294
현지   1.386294
화석   1.386294

[66 rows x 1 columns]

In [70]:
result = []


# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
  result.append([])
  d = kospacing_title_list[0]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tfidf(t, d))
        
title_tfidf_ = pd.DataFrame(result, columns = vocab)

In [71]:
title_tfidf_

가능   가짜  갈고리   결과   고대   과정  그동안        나무   남부  뉴시스  ...   지탱   직선   진화  \
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   
18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  0.0  0.0  ...  0.0  0.0  0.0   

     초식   최소   탕바   픽사  현대판   현지        화석  
0   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
1   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
2   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
3   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
4   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
5   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
6   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
7   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
8   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
9   0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
10  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
11  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
12  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
13  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
14  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
15  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
16  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
17  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  
18  0.0  0.0  0.0  0.0  0.0  0.0  1.386294  

[19 rows x 66 columns]

In [72]:
from cosine_similarity import *
import numpy as np

문서 1과 문서2의 유사도 : 0.6666666666666667
문서 1과 문서3의 유사도 : 0.6666666666666667
문서 2와 문서3의 유사도 : 1.0000000000000002
overview 열의 결측값의 수: 135
TF-IDF 행렬의 크기(shape) : (20000, 47487)
코사인 유사도 연산 결과 : (20000, 20000)
4


In [73]:
# np.linalg.norm(title_tf_.values)
# np.linalg.det(title_tf_.values, content_tf_.values)

In [75]:
dot(title_tf_.values, content_tf_.values.T)

array([[0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 0, 6, 0],
       [0,

In [76]:
norm(title_tf_.values)

8.717797887081348

In [77]:
norm(content_tf_.values.T)

11.224972160321824

In [78]:
cos_sim = dot(title_tf_.values, content_tf_.values.T)/(norm(title_tf_.values)*norm(content_tf_.values.T))
cos_sim.shape

(19, 19)

In [79]:
cosine_similarity(title_tf_.values, content_tf_.values).shape == cos_sim.shape

True

## 100개의 특정표본을 이용하여서 처리화하기

In [80]:
whole_title_noun = []
for chosun_title in chosun_eilbo_database.head(100)["title"]:
    kospacing_title_list = []
    list1 = str(chosun_title).split('.')
    for i in list1:
        i_list1 = i.split(',')
        for i_2 in i_list1:
            kospacing_title_list.append(i_2.strip())
    title_noun = []
    for title in kospacing_title_list:
        for noun in extract_noun_from_kiwi_analyzed(title):
            if len(noun) < 2:
                continue
            else:
                title_noun.append(noun)
    title_noun = list(set(title_noun))
    whole_title_noun.append(title_noun)
print(whole_title_noun)

[['대나무', '화석', '언제'], ['이준석', '수사', '경기', '요청', '결과', '기각', '징계', '변호인', '변호사회'], ['꼰대', '이광재', '배후', '사고', '박지현'], ['반성', '검수', '모드', '주자', '당권'], ['시누이', '부부', '여성', '메탄올', '시야', '음식'], ['주차비', '레고랜드', '시간'], ['규제', '백악관', '낙태', '가스', '연방대법원', '온실', '제동', '퇴행', '결정'], ['운명', '이준석', '마중', '박지원', '귀국길'], ['이상', '수비대', '혁명', '숙청', '이란', '징후', '사망', '정권', '보루', '지휘관'], ['아파트', '오데사', '쑥대밭'], ['친형', '공무원', '피살', '라면', '조롱', '유족', '목구멍'], ['패션', '길거리', '제냐', '회장', '서울', '이탈리아', '이유', '기업'], ['인사', '대통령', '갈등', '하락', '논란', '지지율', '당내'], ['시위', '전장', '이준석', '민주당', '휠체어', '해결', '체험'], ['출마', '이재명', '영입', '고민', '박지현'], ['유포', '고교', '얼굴', '영상', '친구', '합성', '포르노'], ['동화', '작가', '클린', '빈센트'], ['메르켈', '퇴임', '인권', '심사', '직책', '위원장'], ['드라마', '착수', '미남', '고용부', '근로', '감독', '제작사', '단독', '이유'], ['민주', '부부', '해외', '악평', '순방', '성적표'], ['시위', '민노총', '전국', '검찰', '작년', '불법', '기소'], ['인증', '폭염', '가재', '사진', '논물'], ['상납', '이준석', '인멸', '녹취록', '조각', '증거', '편집'], ['기증', '학생', '장기', '부산', '생명', '출범', '서포터즈'], ['

In [81]:
whole_content_sentence_list = []
count = 1
for chosun_url in chosun_eilbo_database.head(100)["url"]:
    headers = {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"}
    response_0 = requests.get(chosun_url, headers=headers)
    soup_0 = BeautifulSoup(response_0.text, 'html.parser')
    content_0_data = soup_0.find('div', {"id" : "dic_area"})
    # print(count)
    if content_0_data == None:
        content_0_data = np.NaN
        whole_content_sentence_list.append(content_0_data)
    else:
        content_0_data = content_0_data.get_text().strip()
        content_0_data = content_0_data.replace('\n','').replace('\t','')
        new_content_0_data = content_0_data.replace(" ", '')
        kospacing_new_content_0_data = spacing(new_content_0_data) 
        words_data = twitter.morphs(kospacing_new_content_0_data)
        with open("C:\\Users\\user\\Documents\\github\\bigdata_thunder\\bigdata2\\korean_stopwords.txt", "r", encoding="UTF-8") as stopwords:
            stopwords_list = stopwords.read().split('\n')
        new_content_1 ='' 
        for i in korean_change_no_stop_words(words_data, stopwords_list):
            new_content_1 += i
        # print(new_content_1)
        tokenizer3_content_1 = RegexpTokenizer('[A-Za-z0-9ㄱ-ㅎ/()]+', gaps=True)
        # tokenizer3_content_2 = RegexpTokenizer('')
        # print(tokenizer3_content_1.tokenize(new_content_1))
        regular_expression_sentence = ''
        for expression in tokenizer3_content_1.tokenize(new_content_1):
            regular_expression_sentence += expression
        whole_content_sentence_list.append(regular_expression_sentence) 
    
    # print()
    # count += 1
# print(whole_content_sentence_list)

1/1 [==============================] - 0s 21ms/step


In [82]:
print(whole_content_sentence_list)

['판다.픽사베이통통한몸집어울리지않게대나무주식하는판다.판다독특한식성최소만년터이어졌을가능성있다는연구결과나왔다.일현지외신따르면미국로스앤젤레스자연사박물관왕샤오밍박사연구팀은최근약만년전자이언트판다조상인일루락토스화석분석한결과,대나무잡는데쓰이는‘가짜엄지’존재했다고밝혔다.화석은중국남부윈난성자오퉁시슈이탕바지역발굴됐다.약만년전살았던고대판다일루락토스이다.눈여겨볼은손목부위발견된돌출뼈다.연구팀은뼈자이언트판다가진번째손가락일명‘가짜엄지’라고말했다.판다가짜엄지.뉴시스판다가짜엄지는대나무보다쉽게잡수있도록하는데쓰인다.판다초식동물진화하는데중추적인역할했을전문가들은보고.그동안같은진화적적응은약만년전인비교적최근이뤄진여겨져왔는데,연구무려만년거슬러올라간다는증명해낸셈이다.화석발견된가짜엄지는현대판다보다더긴길이직선모양하고있었다.연구팀은“가짜엄지는대나무잡고뜯어먹을는먹이찾아걸어갈몸무게지탱하는용도도쓰이는데,과정긴뼈짧은갈고리형진화하게된”이라고분석했다.왕박사는“대나무먹기좋게쪼개기위해줄기단단히붙잡는은많은양대나무먹는데가장중요한적응”라며“육식성조상진화해대나무만먹는종바뀐판다는많은장애넘어야했을이고가짜엄지는중가장놀라운진화”라고설명했다.', '“가세연이준석녹취는일부삭제된”국민힘준석대표.연합뉴스경기중앙지방변호사회한보수단체제기한이준석국민힘대표변호인징계진정기각한일확인됐다.앞서보수단체인‘자유대한호국단’은이준석대표변호인인김연기변호사대표‘성상납증거인멸교사’의혹공동정범고발하고대한변호사협회김변호사대한징계처분요청했다.경기중앙지방변호사회는지난달일자기각결정내리고이사실통보했다.변호사회는기각유서“진정인은가로세로연구소공개한통화녹취록근거피진정인증거인멸시도했다는취지주장하고있으나,위통화녹취록은대화일부삭제된보인다”라고했다.진정인측김변호사증거인멸공동정범고발한대해서도“아직대한수사결과오지않은상황진정인제출한증거만으로는피진정인사실확인서증거조작거나허위진술교사했다고단정기어렵다”라며“피진정인징계개시사유있다고볼수없어,사건진정기각한다”라고했다.', "비대위원장직진사퇴후한달만에공개행사참석재명전당대회출마민형배복당반대입장밝혀박지현전더불어민주당비상대책위원장일서울여의도국회의원회관열린그린벨트

In [95]:
whole_content_noun = []
count = 1
for content in whole_content_sentence_list:
    # kospacing_sent_list = []
    if type(content) == float:
       whole_content_noun.append([np.NaN])
    #    print(count)
       count+=1
    else:
        # print(count)
        content = spacing(content)
        list1 = content.split('.')
        count+=1
        for i in list1:
            i_list1 = i.split(',')
            # print(i_list1)
            for i_2 in i_list1:
                kospacing_sent_list.append(i_2.strip())
            # print(kospacing_sent_list)
        content_noun = []
        for content in kospacing_sent_list:
            for noun in extract_noun_from_kiwi_analyzed(content):
                if len(noun) < 2:
                    continue
                else:
                    content_noun.append(noun)
#         content_noun = list(set(content_noun))
#         content_noun = content_noun.sort()
#         whole_content_noun.append(content_noun)
# print(whole_content_noun)
            

1/1 [==============================] - 0s 21ms/step
['판다']
['픽사 베이통통한 몸집 어울리지 않게 대나무 주식하는 판다']
[' 판다독특한 식성 최소 만년 터이어졌을 가능성 있다는 연구 결과 나왔다']
[' 일 현지 외신 따르면 미국 로스앤젤레스 자연사박물관 왕샤오밍 박사 연구팀은 최근 약 만년 전자이언트 판다 조상인 일루락토스 화 석 분석한 결과', ' 대나무 잡는데 쓰이는 ‘가짜 엄지’ 존재했다고 밝혔다']
[' 화석은 중국 남부 윈난성 자오퉁시 슈이 탕바지역 발굴됐다']
['약 만년 전 살았던 고대 판다일루락토스이다']
[' 눈여겨볼은 손목 부위 발견된 돌출뼈다']
[' 연구팀은 뼈 자이언트 판다가 진번째 손가락 일명 ‘가짜 엄지’라고 말했다']
[' 판다가짜 엄지']
['뉴시스판다가짜 엄지는 대나무보다 쉽게 잡수 있도록 하는 데 쓰인다']
[' 판다초식 동물 진화하는데 중추적인 역할했을 전문가들은 보고']
[' 그동안 같은 진화적 적응은 약 만년 전 인 비교적 최근 이뤄진 여겨져 왔는데', ' 연구 무려 만년 거슬러 올라간다는 증명해낸 셈이다']
[' 화석 발견된 가짜 엄지는 현대판다보다 더 긴 길이 직선 모양하고 있었다']
['연구팀은 “가짜 엄지는 대나무 잡고 뜯어먹을는 먹이 찾아 걸어갈 몸무게 지탱하는 용도도 쓰이는데', ' 과정 긴 뼈 짧은 갈고리형 진화하게 된”이라고 분석했다']
[' 왕 박사는 “대나무 먹기 좋게 쪼개기 위해 줄기 단단히 붙잡는 은 많은 양대나무 먹는데 가장 중요한 적응”라며 “육식성 조상 진화해대나무만 먹는 종 바뀐 판다는 많은 장애 넘어야 했을 이고 가짜 엄지는 중 가장 놀라운 진화”라고 설명했다']
['']
1/1 [==============================] - 0s 21ms/step
['“가세연이준석 녹취는 일부 삭제된” 국민 힘 준석 대표']
['연합뉴스 경기중앙지방변호사회 한보수단체 제기한 이준석 국민힘 대표변호인징계진정기각한일 확인됐다']
[' 앞서 보수

In [3]:
title_vocab = {}
title_preprocessed_sentences = []

for newspaper_title in chosun_eilbo_database["title"]:
    newspaper_title_0 = newspaper_title.replace(" ", '')
    kospacing_new_title_0_data = spacing(newspaper_title_0) 
    print(kospacing_new_title_0_data)
    with open("C:\\bigdata_git\\bigdata_thunder\\bigdata2\\korean_stopwords.txt", "r", encoding="UTF-8") as stopwords:
        stopwords_list = stopwords.read().split('\n')
    new_title_1 ='' 
    for newspaper_title_word in korean_change_no_stop_words(kospacing_new_title_0_data, stopwords_list):
        new_title_1 += newspaper_title_word
    tokenizer3_title_1 = RegexpTokenizer('[A-Za-z0-9ㄱ-ㅎ/()]+', gaps=True)
    title_regular_expression_sentence = ''
    for expression in tokenizer3_content_1.tokenize(new_content_1):
        title_regular_expression_sentence += expression
    for title_sentence in sent_tokenize(title_regular_expression_sentence):
        # 단어 토큰화
        word_result = []
        title_tokenized_sentence = twitter.nouns(title_sentence)
        for word in title_tokenized_sentence: 
            if len(word) > 2: 
                word_result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1
        title_preprocessed_sentences.append(word_result) 

        

NameError: name 'chosun_eilbo_database' is not defined